#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(dirname "$SCRIPT_DIR")"
INFRA_DIR="$ROOT_DIR/infrastructure"

# Usage
if [ $# -lt 1 ]; then
  echo "Usage: ./scripts/setup-infra.sh <domain1,domain2,...>"
  echo ""
  echo "Generates Caddyfile and docker-compose site configs from templates."
  echo ""
  echo "Example:"
  echo "  ./scripts/setup-infra.sh acme.com,shop.acme.com,blog.acme.com"
  exit 1
fi

# Parse comma-separated domains
IFS=',' read -ra DOMAINS <<< "$1"

# Validate domains — alphanumeric, hyphens, dots only. Blocks Caddyfile injection.
for d in "${DOMAINS[@]}"; do
  if [[ ! "$d" =~ ^[a-zA-Z0-9]([a-zA-Z0-9.-]*[a-zA-Z0-9])?$ ]] || [[ "$d" == *..* ]]; then
    echo "Error: Invalid domain '$d'. Use only letters, numbers, hyphens, and dots."
    exit 1
  fi
done

echo "Setting up infrastructure for ${#DOMAINS[@]} site(s):"
for d in "${DOMAINS[@]}"; do echo "  - $d"; done
echo ""

# 1. Generate Caddyfile
CADDYFILE="$INFRA_DIR/Caddyfile"
cat > "$CADDYFILE" << 'HEADER'
# Caddyfile — Generated by Astro Fleet setup-infra.sh
# Serves static sites built by Astro behind Traefik.

HEADER

for DOMAIN in "${DOMAINS[@]}"; do
  SLUG=$(echo "$DOMAIN" | tr '.' '-')
  cat >> "$CADDYFILE" << SITEEOF
@${SLUG} host ${DOMAIN} www.${DOMAIN}
handle @${SLUG} {
  root * /srv/${DOMAIN}
  encode gzip
  file_server {
    precompressed gzip br
  }
  header {
    Cache-Control "public, max-age=31536000, immutable"
    X-Content-Type-Options "nosniff"
    X-Frame-Options "DENY"
    Referrer-Policy "strict-origin-when-cross-origin"
  }
  @html path *.html /
  header @html Cache-Control "public, max-age=3600, must-revalidate"
  try_files {path} {path}/index.html =404
}

SITEEOF
done

echo "✓ Generated $CADDYFILE (${#DOMAINS[@]} sites)"

# 2. Generate .env from example
if [ ! -f "$INFRA_DIR/.env" ]; then
  cp "$INFRA_DIR/.env.example" "$INFRA_DIR/.env"
  # Fill in random secrets
  if command -v openssl &> /dev/null; then
    RANDOM_PW=$(openssl rand -base64 24)
    sed -i'' -e "s|change_me_to_a_random_string|$RANDOM_PW|g" "$INFRA_DIR/.env"
    find "$INFRA_DIR" -name "*.env-e" -delete 2>/dev/null || true
  fi
  echo "✓ Generated $INFRA_DIR/.env (review and update ACME_EMAIL)"
else
  echo "• Skipped .env (already exists)"
fi

# 3. Print volume mount lines for docker-compose
echo ""
echo "Add these volume mounts to the caddy service in docker-compose.yml:"
echo ""
for DOMAIN in "${DOMAINS[@]}"; do
  echo "  - ../sites/${DOMAIN}/dist:/srv/${DOMAIN}:ro"
done
echo ""
echo "Add these Traefik labels for each site, or use Caddy's auto-HTTPS."
echo ""
echo "Next steps:"
echo "  1. Review infrastructure/.env (set ACME_EMAIL)"
echo "  2. Add volume mounts to docker-compose.yml"
echo "  3. Build all sites: bun run build"
echo "  4. Start: cd infrastructure && docker compose up -d"
